### ISSUE TITLE
Add command usage history

### ISSUE THREAD

**Issue by SchoolyB** [Solitude-Software-Solutions/OstrichDB#103]
Might be beneficial if the user could cycle through and view their command history usage. Exactly like shells do. This could be implemented in to ways. a `HISTORY` command which would probably result in a wall of text.... or by getting the users keyboard input when they use the "up" arrow key and cycle through each individual previous command used .

**Comment by CobbCoding1** [comment]
So from my brainstorming, the HISTORY command seems to be fairly simple, but handling arrow keys will be require a bit more work. I'll need to look into Odin a bit more, but to detect the arrow key in a nice cross-platform way, will probably require a library, and a change to the entire input/output system. Could use something like ncurses, which is what I use for Cano. From what I can tell, it will require basically turning it into a TUI program, rather than a CLI. There may be a smaller and simpler library for just detecting keypresses, but I'm not sure.
I'll look into it a bit more, and I'll leave some more comments here as I continue my research.
